### ISSUE TITLE
broken test archive tests/issues/issue33_1.zip

### ISSUE THREAD

**Issue by dfooz** [Lecrapouille/zipper#2]
Issue33 test fails, 

Ark also doesn't open archive: Couldn't load the archive .....

**Comment by Lecrapouille** [comment]
@dfooz Can you give more details: your operating system, how you build it, how you called my unit tests, are you in the good folder when doing unit tests ? ... Your description is too light for me to help you. Strange since my unit tests passed for Linux and Mac OS, did you notice an issue in my tests ?

**Comment by Lecrapouille** [comment]
Closed because I do not have enough information to fix it. Feel free to re-open it with more feedback.
