### ISSUE TITLE
Please update to Minizip v1.3.1

### ISSUE THREAD

**Issue by noloader** [Lecrapouille/zipper#9]
Please update to Minizip v1.3.1. It is available in Mark Adler's GitHub at <https://github.com/madler/zlib/tree/develop/contrib/minizip>.

**Comment by Lecrapouille** [comment]
@noloader Thanks for the report, I'll check it when I'll time (currently I have few)

**Comment by Lecrapouille** [comment]
I dunno which minizip version I'm using (saggy I know) but my version uses AES encryption while the one you are referring does not have it. So I would say no to your request because I've a (saggy) fresher version. Would be better to track the HEAD of minizip-ng but I cannot: the API has changed too much this will not compile and this is long-time known problem concerning our lib. I'm close feel free to reopen it in case of.

**Comment by Lecrapouille** [comment]
Note: updated with https://github.com/Lecrapouille/zipper/issues/8 with this commit https://github.com/Lecrapouille/minizip/commit/4bc21ffc6ae93da0d3d8f23c119f553c20608679
